# Generated by Django 5.2.17 on 2026-09-29 20:31

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_stockmovement'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('return_number', models.CharField(max_length=30, unique=True)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REFUNDED', 'Refunded'), ('REJECTED', 'Rejected')], max_length=20)),
                ('reason', models.TextField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('inventory_disposition', models.CharField(choices=[('RESTOCK', 'Restock'), ('REPAIR', 'Repair'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('owner_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('refunded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns_approved', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='customers.customer')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='returns_reviewed', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='sales.transaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReturnItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('refund_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('disposition', models.CharField(choices=[('RESTOCK', 'Restock'), ('REPAIR', 'Repair'), ('DAMAGED', 'Damaged')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='inventory.deviceitem')),
                ('return_request', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='returns.return')),
                ('transaction_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='return_items', to='sales.transactionitem')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['status', 'created_at'], name='returns_ret_status_98f0de_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['customer', 'created_at'], name='returns_ret_custome_182352_idx'),
        ),
        migrations.AddIndex(
            model_name='return',
            index=models.Index(fields=['transaction', 'created_at'], name='returns_ret_transac_4d0e00_idx'),
        ),
        migrations.AddConstraint(
            model_name='return',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='return_refund_amount_non_negative'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['return_request', 'id'], name='returns_ret_return__c395b5_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['transaction_item'], name='returns_ret_transac_3bb9fc_idx'),
        ),
        migrations.AddIndex(
            model_name='returnitem',
            index=models.Index(fields=['device'], name='returns_ret_device__1114f8_idx'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='return_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.CheckConstraint(condition=models.Q(('refund_amount__gte', 0)), name='return_item_refund_non_negative'),
        ),
    ]
