# Generated by Django 5.2.17 on 2026-09-30 15:53

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0001_initial'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='return',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='returnitem',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='return',
            name='return_refund_amount_non_negative',
        ),
        migrations.RemoveConstraint(
            model_name='returnitem',
            name='return_item_quantity_positive',
        ),
        migrations.RemoveConstraint(
            model_name='returnitem',
            name='return_item_refund_non_negative',
        ),
        migrations.RemoveIndex(
            model_name='return',
            name='returns_ret_status_98f0de_idx',
        ),
        migrations.RemoveIndex(
            model_name='return',
            name='returns_ret_custome_182352_idx',
        ),
        migrations.RemoveIndex(
            model_name='return',
            name='returns_ret_transac_4d0e00_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnitem',
            name='returns_ret_return__c395b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnitem',
            name='returns_ret_transac_3bb9fc_idx',
        ),
        migrations.RemoveIndex(
            model_name='returnitem',
            name='returns_ret_device__1114f8_idx',
        ),
        migrations.RenameField(
            model_name='return',
            old_name='approved_at',
            new_name='completed_at',
        ),
        migrations.RenameField(
            model_name='returnitem',
            old_name='refund_amount',
            new_name='line_total',
        ),
        migrations.RemoveField(
            model_name='return',
            name='customer_notes',
        ),
        migrations.RemoveField(
            model_name='return',
            name='inventory_disposition',
        ),
        migrations.RemoveField(
            model_name='return',
            name='owner_notes',
        ),
        migrations.RemoveField(
            model_name='return',
            name='refund_amount',
        ),
        migrations.RemoveField(
            model_name='return',
            name='refunded_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='requested_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='reviewed_at',
        ),
        migrations.RemoveField(
            model_name='return',
            name='reviewed_by',
        ),
        migrations.RemoveField(
            model_name='return',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='device',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='disposition',
        ),
        migrations.RemoveField(
            model_name='returnitem',
            name='return_request',
        ),
        migrations.AddField(
            model_name='return',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='return',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='return_record',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='returns.return'),
        ),
        migrations.AddField(
            model_name='returnitem',
            name='unit_refund_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
        migrations.AlterField(
            model_name='return',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='return',
            name='reason',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AddConstraint(
            model_name='returnitem',
            constraint=models.UniqueConstraint(fields=('return_record', 'transaction_item'), name='unique_return_item'),
        ),
    ]
