# Generated by Django 5.2.17 on 2026-09-30 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_alter_return_options_alter_returnitem_options_and_more'),
    ]

    operations = [
    ]
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("returns", "0002_alter_return_options_alter_returnitem_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="return",
            name="created_by",
            field=models.ForeignKey(
                on_delete=models.deletion.PROTECT,
                related_name="created_returns",
                to="users.user",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="return_record",
            field=models.ForeignKey(
                on_delete=models.deletion.CASCADE,
                related_name="items",
                to="returns.return",
            ),
        ),
        migrations.AlterField(
            model_name="returnitem",
            name="unit_refund_amount",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=12,
                validators=[],
            ),
        ),
    ]