# Generated by Django 5.2.17 on 2026-09-30 17:09

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_make_return_fields_required'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('RESTOCKED', 'Restocked'), ('REJECTED', 'Rejected'), ('REFUNDED', 'Refunded')], default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='unit_refund_amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
