# Generated by Django 5.2.17 on 2026-09-29 19:49

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('reorder_level', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='accessory_stock', to='catalog.product')),
            ],
            options={
                'ordering': ['product__name'],
                'indexes': [models.Index(fields=['quantity'], name='inventory_a_quantit_59cd73_idx'), models.Index(fields=['reorder_level'], name='inventory_a_reorder_1f325b_idx')],
            },
        ),
        migrations.CreateModel(
            name='DeviceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imei_1', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('imei_2', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('default_selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('minimum_selling_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('battery_health', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('condition', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], default='A', max_length=1)),
                ('status', models.CharField(choices=[('RECEIVED', 'Received'), ('IN_STOCK', 'In Stock'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('REPAIR', 'Repair'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], default='RECEIVED', max_length=20)),
                ('received_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='device_items', to='catalog.product')),
            ],
            options={
                'ordering': ['-received_at'],
                'indexes': [models.Index(fields=['product', 'status'], name='inventory_d_product_f77676_idx'), models.Index(fields=['status'], name='inventory_d_status_3e2cd5_idx'), models.Index(fields=['condition'], name='inventory_d_conditi_9fae4b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('imei_1__isnull', False), ('serial_number__isnull', False), _connector='OR'), name='device_identifier_required'), models.CheckConstraint(condition=models.Q(('imei_2__isnull', True), models.Q(('imei_2', models.F('imei_1')), _negated=True), _connector='OR'), name='imei_2_different_from_imei_1'), models.CheckConstraint(condition=models.Q(('minimum_selling_price__lte', models.F('default_selling_price'))), name='minimum_price_lte_default_price')],
            },
        ),
    ]
