# Generated by Django 5.2.17 on 2026-09-29 19:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('RECEIVED', 'Received'), ('SALE', 'Sale'), ('COMPLIMENTARY', 'Complimentary'), ('RETURN', 'Return'), ('DAMAGE', 'Damage'), ('LOSS', 'Loss'), ('ADJUSTMENT', 'Adjustment'), ('RESERVED', 'Reserved'), ('RESERVATION_RELEASED', 'Reservation Released'), ('SOLD', 'Sold'), ('RETURNED', 'Returned'), ('REPAIR', 'Repair'), ('REPAIR_COMPLETED', 'Repair Completed'), ('DAMAGED', 'Damaged'), ('LOST', 'Lost'), ('EXCHANGE_OUT', 'Exchange Out'), ('EXCHANGE_IN', 'Exchange In')], max_length=30)),
                ('quantity', models.IntegerField()),
                ('from_status', models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('IN_STOCK', 'In Stock'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('REPAIR', 'Repair'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], max_length=20, null=True)),
                ('to_status', models.CharField(blank=True, choices=[('RECEIVED', 'Received'), ('IN_STOCK', 'In Stock'), ('RESERVED', 'Reserved'), ('SOLD', 'Sold'), ('REPAIR', 'Repair'), ('LOST', 'Lost'), ('DAMAGED', 'Damaged')], max_length=20, null=True)),
                ('reference_type', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_id', models.BigIntegerField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.accessorystock')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='stock_movements', to='inventory.deviceitem')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['device', 'created_at'], name='inventory_s_device__4d8fde_idx'), models.Index(fields=['accessory_stock', 'created_at'], name='inventory_s_accesso_1e53a3_idx'), models.Index(fields=['movement_type', 'created_at'], name='inventory_s_movemen_ed5291_idx'), models.Index(fields=['reference_type', 'reference_id'], name='inventory_s_referen_5aaa1a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0), ('quantity__lt', 0), _connector='OR'), name='stock_movement_quantity_nonzero'), models.CheckConstraint(condition=models.Q(models.Q(('accessory_stock__isnull', True), ('device__isnull', False)), models.Q(('accessory_stock__isnull', False), ('device__isnull', True)), _connector='OR'), name='stock_movement_exactly_one_stock_target')],
            },
        ),
    ]
