# Generated by Django 5.2.17 on 2026-09-29 20:28

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_stockmovement'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=30, unique=True)),
                ('reserved_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('reserved_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('EXPIRED', 'Expired')], max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cancelled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_cancelled', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservations_completed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='customers.customer')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='inventory.deviceitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reservations', to='sales.transaction')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'expires_at'], name='reservation_status_f2f985_idx'), models.Index(fields=['customer', 'status'], name='reservation_custome_e440be_idx'), models.Index(fields=['device', 'status'], name='reservation_device__4cbcbc_idx'), models.Index(fields=['transaction'], name='reservation_transac_ab3395_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('reserved_price__gte', 0)), name='reservation_price_non_negative'), models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('reserved_at'))), name='reservation_expiry_after_start'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('customer',), name='one_active_reservation_per_customer'), models.UniqueConstraint(condition=models.Q(('status', 'ACTIVE')), fields=('device',), name='one_active_reservation_per_device')],
            },
        ),
    ]
