# Generated by Django 5.2.17 on 2026-09-29 20:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_stockmovement'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WarrantyClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_number', models.CharField(max_length=30, unique=True)),
                ('opened_at', models.DateTimeField()),
                ('problem_description', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('UNDER_REVIEW', 'Under Review'), ('REPAIR', 'Repair'), ('SALE_CANCELLED', 'Sale Cancelled'), ('REJECTED', 'Rejected'), ('RESOLVED', 'Resolved')], max_length=20)),
                ('resolution', models.TextField(blank=True, null=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('owner_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='customers.customer')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='inventory.deviceitem')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims_resolved', to=settings.AUTH_USER_MODEL)),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='sales.transaction')),
                ('transaction_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warranty_claims', to='sales.transactionitem')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='warranty_wa_status_0ec285_idx'), models.Index(fields=['customer', 'created_at'], name='warranty_wa_custome_58ddf8_idx'), models.Index(fields=['transaction', 'created_at'], name='warranty_wa_transac_4c2f1c_idx'), models.Index(fields=['device', 'created_at'], name='warranty_wa_device__449abd_idx')],
            },
        ),
    ]
