# Generated by Django 5.2.17 on 2026-09-29 20:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('PRICE_OVERRIDE', 'Price Override'), ('PAYMENT_CONFIRMED', 'Payment Confirmed'), ('PAYMENT_REJECTED', 'Payment Rejected'), ('RESERVATION_CREATED', 'Reservation Created'), ('RESERVATION_CANCELLED', 'Reservation Cancelled'), ('RESERVATION_EXPIRED', 'Reservation Expired'), ('RESERVATION_PRICE_CHANGED', 'Reservation Price Changed'), ('WARRANTY_APPROVED', 'Warranty Approved'), ('WARRANTY_REJECTED', 'Warranty Rejected'), ('RETURN_APPROVED', 'Return Approved'), ('RETURN_REJECTED', 'Return Rejected'), ('EXCHANGE_APPROVED', 'Exchange Approved'), ('EXCHANGE_REJECTED', 'Exchange Rejected'), ('STOCK_ADJUSTED', 'Stock Adjusted'), ('DEVICE_STATUS_CHANGED', 'Device Status Changed'), ('USER_CREATED', 'User Created'), ('USER_UPDATED', 'User Updated'), ('USER_DEACTIVATED', 'User Deactivated'), ('SETTINGS_CHANGED', 'Settings Changed')], max_length=50)),
                ('entity_type', models.CharField(max_length=100)),
                ('entity_id', models.BigIntegerField()),
                ('old_values', models.JSONField(blank=True, null=True)),
                ('new_values', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', 'created_at'], name='audit_audit_actor_i_ec0f72_idx'), models.Index(fields=['action', 'created_at'], name='audit_audit_action_766c6d_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx'), models.Index(fields=['created_at'], name='audit_audit_created_2c1626_idx')],
            },
        ),
    ]
