# Generated by Django 5.2.17 on 2026-09-29 20:32

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_stockmovement'),
        ('sales', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exchange_number', models.CharField(max_length=30, unique=True)),
                ('old_device_value', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('new_device_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('difference_amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('financial_direction', models.CharField(choices=[('CUSTOMER_PAYS', 'Customer Pays'), ('STORE_REFUNDS', 'Store Refunds'), ('EVEN', 'Even')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('UNDER_REVIEW', 'Under Review'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], max_length=20)),
                ('reason', models.TextField(blank=True, null=True)),
                ('owner_notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_approved', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_completed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='customers.customer')),
                ('new_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_as_new_device', to='inventory.deviceitem')),
                ('old_device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_as_old_device', to='inventory.deviceitem')),
                ('original_transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exchanges', to='sales.transaction')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='exchanges_reviewed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='exchanges_e_status_8f276a_idx'), models.Index(fields=['customer', 'created_at'], name='exchanges_e_custome_edf755_idx'), models.Index(fields=['original_transaction', 'created_at'], name='exchanges_e_origina_6def42_idx'), models.Index(fields=['old_device'], name='exchanges_e_old_dev_ddc2f6_idx'), models.Index(fields=['new_device'], name='exchanges_e_new_dev_9a05df_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('old_device_value__gte', 0)), name='exchange_old_value_non_negative'), models.CheckConstraint(condition=models.Q(('new_device_price__gte', 0)), name='exchange_new_price_non_negative'), models.CheckConstraint(condition=models.Q(('difference_amount__gte', 0)), name='exchange_difference_non_negative'), models.CheckConstraint(condition=models.Q(('old_device', models.F('new_device')), _negated=True), name='exchange_devices_must_differ')],
            },
        ),
    ]
