# Generated by Django 5.2.17 on 2026-09-29 19:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_device', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('brand', models.CharField(max_length=100)),
                ('platform', models.CharField(choices=[('APPLE', 'Apple'), ('ANDROID', 'Android'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('storage_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('ram_gb', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category')),
            ],
            options={
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['category', 'is_active'], name='catalog_pro_categor_891fe8_idx'), models.Index(fields=['brand', 'name'], name='catalog_pro_brand_5bba97_idx'), models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx')],
            },
        ),
    ]
