# Generated by Django 5.2.17 on 2026-09-29 20:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=16, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('total_spent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['full_name', 'id'],
                'indexes': [models.Index(fields=['full_name'], name='customers_c_full_na_70c97a_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('total_spent__gte', 0)), name='customer_total_spent_non_negative')],
            },
        ),
    ]
