# Generated by Django 5.2.17 on 2026-09-29 20:33

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_number', models.CharField(max_length=30, unique=True)),
                ('source_type', models.CharField(choices=[('RETURN', 'Return'), ('EXCHANGE', 'Exchange'), ('RESERVATION', 'Reservation'), ('OVERPAYMENT', 'Overpayment'), ('WARRANTY', 'Warranty')], max_length=20)),
                ('source_id', models.BigIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('method', models.CharField(choices=[('CASH', 'Cash'), ('BANK_TRANSFER', 'Bank Transfer')], max_length=20)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('COMPLETED', 'Completed')], max_length=20)),
                ('reference', models.CharField(blank=True, max_length=150, null=True)),
                ('reason', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('requested_at', models.DateTimeField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('rejected_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('completed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_completed', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='customers.customer')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refunds_rejected', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='RefundPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_allocations', to='payments.payment')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_allocations', to='refunds.refund')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['status', 'created_at'], name='refunds_ref_status_daa6e4_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['customer', 'created_at'], name='refunds_ref_custome_e6b013_idx'),
        ),
        migrations.AddIndex(
            model_name='refund',
            index=models.Index(fields=['source_type', 'source_id'], name='refunds_ref_source__73124e_idx'),
        ),
        migrations.AddConstraint(
            model_name='refund',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_positive'),
        ),
        migrations.AddIndex(
            model_name='refundpaymentallocation',
            index=models.Index(fields=['refund'], name='refunds_ref_refund__20175c_idx'),
        ),
        migrations.AddIndex(
            model_name='refundpaymentallocation',
            index=models.Index(fields=['payment'], name='refunds_ref_payment_e70b87_idx'),
        ),
        migrations.AddConstraint(
            model_name='refundpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_allocation_amount_positive'),
        ),
        migrations.AddConstraint(
            model_name='refundpaymentallocation',
            constraint=models.UniqueConstraint(fields=('refund', 'payment'), name='unique_refund_payment_allocation'),
        ),
    ]
