# Generated by Django 5.2.17 on 2026-09-29 20:19

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        ('inventory', '0002_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_id', models.CharField(max_length=30, unique=True)),
                ('transaction_type', models.CharField(choices=[('SALE', 'Sale'), ('RESERVATION', 'Reservation')], max_length=20)),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING_PAYMENT', 'Pending Payment'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], max_length=20)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('total_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='customers.customer')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='TransactionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name_snapshot', models.CharField(max_length=200)),
                ('sku_snapshot', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('price_sold', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('cost_price_at_sale', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('is_complimentary', models.BooleanField(default=False)),
                ('warranty_start', models.DateField(blank=True, null=True)),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accessory_stock', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='inventory.accessorystock')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='transaction_items', to='inventory.deviceitem')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='sales.transaction')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['status', 'created_at'], name='sales_trans_status_5c4a9b_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['transaction_type', 'created_at'], name='sales_trans_transac_71120d_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['customer', 'created_at'], name='sales_trans_custome_9db8bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('subtotal__gte', 0)), name='transaction_subtotal_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('discount_amount__gte', 0)), name='transaction_discount_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transaction',
            constraint=models.CheckConstraint(condition=models.Q(('total_amount__gte', 0)), name='transaction_total_non_negative'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['transaction', 'id'], name='sales_trans_transac_a91ba3_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['device'], name='sales_trans_device__41ead0_idx'),
        ),
        migrations.AddIndex(
            model_name='transactionitem',
            index=models.Index(fields=['accessory_stock'], name='sales_trans_accesso_21a53e_idx'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('accessory_stock__isnull', True), ('device__isnull', False)), models.Q(('accessory_stock__isnull', False), ('device__isnull', True)), _connector='OR'), name='transaction_item_exactly_one_stock_target'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='transaction_item_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='transaction_item_unit_price_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('price_sold__gte', 0)), name='transaction_item_price_sold_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('line_total__gte', 0)), name='transaction_item_line_total_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('cost_price_at_sale__gte', 0)), name='transaction_item_cost_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transactionitem',
            constraint=models.CheckConstraint(condition=models.Q(('is_complimentary', False), ('price_sold', 0), _connector='OR'), name='complimentary_item_price_zero'),
        ),
    ]
