# Generated by Django 5.2.17 on 2026-09-30 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('SALE', 'Sale'), ('RESERVATION', 'Reservation'), ('EXCHANGE', 'Exchange')], max_length=20),
        ),
    ]
